In [28]:
import torch

In [29]:
material_cost=torch.tensor(10, requires_grad=True, dtype=torch.float16)
labor_cost=torch.tensor(5, requires_grad=True, dtype=torch.float16)

total_cost=3*material_cost**2 + 5*labor_cost + 100
total_cost

tensor(425., dtype=torch.float16, grad_fn=<AddBackward0>)

In [30]:
total_cost.backward()


In [31]:
material_cost.grad, labor_cost.grad

(tensor(60., dtype=torch.float16), tensor(5., dtype=torch.float16))

In [32]:
total_cost.requires_grad

True

In [33]:
x = torch.tensor(4, requires_grad=True, dtype=torch.float16)
y = x**2 + 5
print("outside no grad: ", y.requires_grad)

with torch.no_grad():
    y = x**2 + 5 
    print("inside no_grad: ", y.requires_grad)

outside no grad:  True
inside no_grad:  False


In [34]:
## gradient for vectors

x = torch.tensor([1, 2, 3], requires_grad=True, dtype=torch.float16)

y = 2*x**3 + 7
y

tensor([ 9., 23., 61.], dtype=torch.float16, grad_fn=<AddBackward0>)

In [35]:
result = y.sum()
result

tensor(93., dtype=torch.float16, grad_fn=<SumBackward0>)

In [36]:
x = torch.tensor([[1,2],[3,4]],requires_grad=True,dtype=torch.float16)
y = 2*x**3 + 7
y

tensor([[  9.,  23.],
        [ 61., 135.]], dtype=torch.float16, grad_fn=<AddBackward0>)

In [37]:
result = y.sum()
result

tensor(228., dtype=torch.float16, grad_fn=<SumBackward0>)

In [38]:
result.backward()

In [39]:
x.grad

tensor([[ 6., 24.],
        [54., 96.]], dtype=torch.float16)