In [1]:
import torch

In [2]:
torch.tensor(9)

tensor(9)

In [8]:
## array as tensor

revenue = torch.tensor([100, 120, 90, 75])
revenue.shape
revenue

tensor([100, 120,  90,  75])

In [9]:
revenue[1], revenue[0]

(tensor(120), tensor(100))

In [10]:
revenue[:3]

tensor([100, 120,  90])

In [12]:
expense = torch.tensor([80, 117, 71, 68])
expense

tensor([ 80, 117,  71,  68])

In [13]:
profit = revenue - expense
profit

tensor([20,  3, 19,  7])

In [14]:
profit_pct = profit * 100/ revenue
profit_pct

tensor([20.0000,  2.5000, 21.1111,  9.3333])

## metrices as tensor

In [15]:
q1 = torch.tensor(
    [
        [200, 220, 250],
        [150, 180, 210],
        [300, 330, 360]
    ]
    
)


q2 = torch.tensor([
    [209, 231, 259],
    [155, 192, 222],
    [310, 340, 275]
])

In [16]:
## total revenue from q1 and q2

revenue = q1 + q2
revenue

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 635]])

In [17]:
## revenue growth in q2 as compared to q1

revenue_growth2 = q2 - q1
revenue_growth2

tensor([[  9,  11,   9],
        [  5,  12,  12],
        [ 10,  10, -85]])

In [19]:
## sales unit growth in q2 as compared to q1

salesunit_growth2 = ((q2-q1)/q1)*100
salesunit_growth2

tensor([[  4.5000,   5.0000,   3.6000],
        [  3.3333,   6.6667,   5.7143],
        [  3.3333,   3.0303, -23.6111]])