In [1]:
import torch


In [2]:
units = torch.tensor([
    [200, 220],  # Product A (iPhone)
    [150, 180],  # Product B (iPad)
    [300, 330]   # Product C (MacBook)
])

In [3]:
units.shape

torch.Size([3, 2])

In [4]:
units.dtype

torch.int64

In [5]:
units.device

device(type='cpu')

In [6]:
units.view(-1)


tensor([200, 220, 150, 180, 300, 330])

In [7]:
units.view(2,3)


tensor([[200, 220, 150],
        [180, 300, 330]])

In [8]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]])

In [9]:
units

tensor([[200, 220],
        [150, 180],
        [300, 330]])

In [10]:
units[2,0]

tensor(300)

In [11]:
units[2,0] = 305
units

tensor([[200, 220],
        [150, 180],
        [305, 330]])

In [12]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
torch.rand((3,5))

tensor([[0.8970, 0.1063, 0.7615, 0.9974, 0.2529],
        [0.5159, 0.4653, 0.0051, 0.9865, 0.9320],
        [0.3517, 0.8536, 0.6134, 0.6419, 0.6870]])