In [1]:
import torch

In [2]:
torch.tensor(9)

tensor(9)

In [8]:
## array as tensor

revenue = torch.tensor([100, 120, 90, 75])
revenue.shape
revenue

tensor([100, 120,  90,  75])

In [9]:
revenue[1], revenue[0]

(tensor(120), tensor(100))

In [10]:
revenue[:3]

tensor([100, 120,  90])

In [12]:
expense = torch.tensor([80, 117, 71, 68])
expense

tensor([ 80, 117,  71,  68])

In [13]:
profit = revenue - expense
profit

tensor([20,  3, 19,  7])

In [14]:
profit_pct = profit * 100/ revenue
profit_pct

tensor([20.0000,  2.5000, 21.1111,  9.3333])

## metrices as tensor

In [15]:
q1 = torch.tensor(
    [
        [200, 220, 250],
        [150, 180, 210],
        [300, 330, 360]
    ]
    
)


q2 = torch.tensor([
    [209, 231, 259],
    [155, 192, 222],
    [310, 340, 275]
])

In [16]:
## total revenue from q1 and q2

revenue = q1 + q2
revenue

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 635]])

In [17]:
## revenue growth in q2 as compared to q1

revenue_growth2 = q2 - q1
revenue_growth2

tensor([[  9,  11,   9],
        [  5,  12,  12],
        [ 10,  10, -85]])

In [19]:
## sales unit growth in q2 as compared to q1

salesunit_growth2 = ((q2-q1)/q1)*100
salesunit_growth2

tensor([[  4.5000,   5.0000,   3.6000],
        [  3.3333,   6.6667,   5.7143],
        [  3.3333,   3.0303, -23.6111]])

In [20]:
## return items


return_rate = 0.1
return_q1 = return_rate*q1

return_q1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

In [21]:
## profit per unit

profit_per_unit = torch.tensor([
    [30, 27, 25],
    [20, 18, 17],
    [45, 38, 39]
])

profit_perunitq1 = profit_per_unit*q1
profit_perunitq1

tensor([[ 6000,  5940,  6250],
        [ 3000,  3240,  3570],
        [13500, 12540, 14040]])

In [30]:
product_prices = torch.tensor([[1100, 450, 1500]])
product_prices.shape

torch.Size([1, 3])

In [23]:
q1

tensor([[200, 220, 250],
        [150, 180, 210],
        [300, 330, 360]])

In [25]:
revenue_per_region_matrix = torch.matmul(product_prices, q1)
revenue_per_region_matrix

tensor([[737500, 818000, 909500]])

In [29]:
product_prices.t().shape

torch.Size([3, 1])

In [27]:
prices_by_region = q1*product_prices.t()
prices_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [28]:
prices_by_region.sum(dim=0)

tensor([737500, 818000, 909500])

In [31]:
portfolio_composition = torch.tensor([
    [100.0, 50.0, 30.0],
    [80.0, 70.0, 20.0],
    [60.0, 40.0, 90.0]
],dtype=torch.float32)

price_changes = torch.tensor([
    [1.15, 1.05, 0.85],  # Stocks
    [1.05, 1.02, 1.10],  # Bonds
    [1.10, 1.00, 0.90]  # Real estate
], dtype=torch.float32)

values = torch.matmul(portfolio_composition, price_changes)
values


tensor([[200.5000, 186.0000, 167.0000],
        [187.5000, 175.4000, 163.0000],
        [210.0000, 193.8000, 176.0000]])

In [32]:
values_inr = 83*values
values_inr

tensor([[16641.5000, 15437.9990, 13861.0000],
        [15562.5000, 14558.1992, 13529.0000],
        [17430.0000, 16085.3994, 14608.0000]])

In [34]:
torch.cuda.is_available()

False

In [35]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print(device)

mps


In [36]:
# Simulating customer data with 1 million customers and 3 features (age, spending score, income)

customer_data = torch.rand(1_000_000, 3, device=device)
customer_data.shape

torch.Size([1000000, 3])

In [37]:
customer_data[:5]

tensor([[0.4330, 0.7087, 0.9779],
        [0.5417, 0.7857, 0.8802],
        [0.5866, 0.8341, 0.6959],
        [0.6740, 0.8895, 0.3159],
        [0.9530, 0.3194, 0.7055]], device='mps:0')

In [38]:
high_spending_customer = customer_data[customer_data[:, 1]>0.5]
high_spending_customer

tensor([[0.4330, 0.7087, 0.9779],
        [0.5417, 0.7857, 0.8802],
        [0.5866, 0.8341, 0.6959],
        ...,
        [0.8825, 0.7199, 0.2697],
        [0.7897, 0.9938, 0.9783],
        [0.3387, 0.9953, 0.5059]], device='mps:0')

In [39]:
high_spending_customer.shape

torch.Size([499532, 3])