In [1]:
import torch


In [2]:
units = torch.tensor([
    [200, 220],  # Product A (iPhone)
    [150, 180],  # Product B (iPad)
    [300, 330]   # Product C (MacBook)
])

In [3]:
units.shape

torch.Size([3, 2])

In [4]:
units.dtype

torch.int64

In [5]:
units.device

device(type='cpu')

In [6]:
units.view(-1)


tensor([200, 220, 150, 180, 300, 330])

In [6]:
units.view(2,3)


tensor([[200, 220, 150],
        [180, 300, 330]])

In [7]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]])

In [8]:
units

tensor([[200, 220],
        [150, 180],
        [300, 330]])

In [9]:
units[2,0]

tensor(300)

In [10]:
units[2,0] = 305
units

tensor([[200, 220],
        [150, 180],
        [305, 330]])

In [11]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
torch.rand((3,5))

tensor([[6.6397e-01, 4.6183e-01, 7.1571e-01, 2.3591e-01, 7.7331e-04],
        [9.4687e-01, 1.0533e-01, 1.3590e-01, 5.8689e-01, 3.4188e-01],
        [4.3739e-01, 8.2844e-01, 3.8866e-01, 4.5818e-01, 2.4415e-01]])